# https://docs.streamlit.io/develop/api-reference/configuration/config.toml

[theme]
base = "dark"
primaryColor = "#5588ff"
# backgroundColor = "#f5f8ff"
# secondaryBackgroundColor = "#e0e9ff"
font = "sans serif"

[client]
toolbarMode = "auto"

[server]
address = "127.0.0.1"
port = 8501
runOnSave = true

[browser]
# serverAddress = "127.0.0.1"
# serverPort = 8501
gatherUsageStats = false
